# -*- coding: utf-8 -*-
"""Empty_Using_AI_to_split_songs_to_multiple_sources.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15_14ym1KNRA275ayXrZQxtQpGD6wrLI-

<figure class="image">
  <img src="https://sigsep.github.io/assets/img/musheader.41c6bf29.png" alt="Dataset illustration">
  <figcaption>Source: MUSDB18 dataset home page (Link in course resources)</figcaption>
</figure>




## Installing dependencies for the project
"""

!apk install ffmpeg
!pip install librosa
!pip install youtube-dl

!pip install spleeter

"""## Import dependencies"""

import librosa
import youtube_dl

from IPython.display import Audio, display, HTML

"""## Dewnload video from youtube 

**Disclaimer: I don’t own the rights to songs mentioned in this course, the copyrights are of the official music creators and labels.**
"""

from IPython.display import HTML
url = "21OMIkbhleU" #@param {type:"string"}
embed_url = "https://www.youtube.com/embed/%s?rel=0&amp;controls=0&amp;showinfo=0" % (url)
HTML('<iframe width="560" height="315" src=' + embed_url + 'frameborder="0" allowfullscreen></iframe>')

def my_hook(d):
    if d['status'] == 'finished':
        print('Done downloading, now converting ...')

ydl_opts = {
    'format': 'bestaudio/best',       
    'outtmpl': 'song.wav',        
    'noplaylist' : True,        
    'progress_hooks': [my_hook],  
}

with youtube_dl.YoutubeDL(ydl_opts) as ydl:
    ydl.download([url])

audio, rate = librosa.load('song.wav', sr=44100, mono=False)

display(Audio(audio[:, 0*rate:70*rate], rate=rate))

"""## Split songs to separate channels using AI


<figure class="image">
  <img src="https://miro.medium.com/max/2824/1*f7YOaE4TWubwaFF7Z1fzNw.png" alt="Dataset illustration">
  <figcaption>Source: UNet — Line by Line Explanation (Link in course resources)</figcaption>
</figure>
"""

!spleeter separate -h

!spleeter separate -i song.wav -p spleeter:4stems -o output

"""## Let's use Audacity to play different parts of the song"""